@startuml

/'SUBSYSTEMS'/

  component gazebo {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component cob_laserscan {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portout cob_laserscan.cob_scan_left as "cob_scan_left" #blue
    portout cob_laserscan.cob_scan_right as "cob_scan_right" #blue
    portout cob_laserscan.cob_scan_front as "cob_scan_front" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component cob_tricycle_controller {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin cob_tricycle_controller.tricycle_controller_cmd_vel_sub as "tricycle_controller/cmd_vel_sub" #blue
    portout cob_tricycle_controller.tf as "tf" #blue
    portout cob_tricycle_controller.odom_diff as "odom_diff" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component robot_state_publisher {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin robot_state_publisher.joint_states as "joint_states" #blue
    portout robot_state_publisher.tf as "tf" #blue
    portout robot_state_publisher.tf_static as "tf_static" #blue
    portout robot_state_publisher.robot_description as "robot_description" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component cob_joint_state {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portout cob_joint_state.joint_states as "joint_states" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }


@enduml